Repository googleapis/java-os-config, pull requests merged in 2020-05, with the labels that each got.

#24 chore: update common templates
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  README.md
  synth.metadata
Labels: automerge, cla: yes

#29 chore: import shared-dependencies and use maven-flatten-plugin
  .gitignore
  google-cloud-os-config/pom.xml
  grpc-google-cloud-os-config-v1/pom.xml
  pom.xml
  proto-google-cloud-os-config-v1/pom.xml
Labels: cla: yes

#31 chore: remove unused properties
  pom.xml
Labels: automerge, cla: yes

#30 samples: fix samples build
  README.md
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.metadata
  synth.py
Labels: cla: yes

#33 feat: add resource names, fix pagination settings
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/OsConfigServiceClient.java
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/OsConfigServiceSettings.java
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/package-info.java
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/stub/GrpcOsConfigServiceStub.java
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/stub/OsConfigServiceStub.java
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/stub/OsConfigServiceStubSettings.java
  google-cloud-os-config/src/test/java/com/google/cloud/osconfig/v1/OsConfigServiceClientTest.java
  proto-google-cloud-os-config-v1/pom.xml
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/InstanceName.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/OsConfigProto.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchDeploymentName.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchDeployments.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchJobName.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchJobs.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/ProjectName.java
  proto-google-cloud-os-config-v1/src/main/proto/google/cloud/osconfig/v1/osconfig_service.proto
  proto-google-cloud-os-config-v1/src/main/proto/google/cloud/osconfig/v1/patch_deployments.proto
  proto-google-cloud-os-config-v1/src/main/proto/google/cloud/osconfig/v1/patch_jobs.proto
  synth.metadata
Labels: cla: yes

#41 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#42 chore: update CONTRIBUTING.md to include code formatting
  CONTRIBUTING.md
  synth.metadata
Labels: automerge, cla: yes, context: full
