Repository googleapis/java-os-config, pull requests merged in 2020-06, with the labels that each got.

#47 chore: regenerate with updated protoc
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchDeployments.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchJobs.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#49 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#50 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#52 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#55 fix: migrate osconfig & agentendpoint to grpc_service_config
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/stub/OsConfigServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#60 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#61 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  grpc-google-cloud-os-config-v1/pom.xml
  pom.xml
Labels: cla: yes

#63 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#70 docs: Fix several broken links in reference documentation
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchDeployments.java
  proto-google-cloud-os-config-v1/src/main/java/com/google/cloud/osconfig/v1/PatchJobs.java
  proto-google-cloud-os-config-v1/src/main/proto/google/cloud/osconfig/v1/patch_deployments.proto
  proto-google-cloud-os-config-v1/src/main/proto/google/cloud/osconfig/v1/patch_jobs.proto
  synth.metadata
Labels: cla: yes, context: full
