Repository googleapis/java-os-config, pull requests merged in 2020-08, with the labels that each got.

#79 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#80 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#69 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: cla: yes

#85 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#87 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#88 test(os-config): add integration test for v1
  google-cloud-os-config/pom.xml
  google-cloud-os-config/src/test/java/com/google/cloud/osconfig/v1/it/ITSystemTest.java
Labels: cla: yes

#91 test: add listPatchJobInstanceDetails SystemTest
  google-cloud-os-config/src/test/java/com/google/cloud/osconfig/v1/it/ITSystemTest.java
Labels: cla: yes

#90 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#92 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
