Repository googleapis/java-os-config, pull requests merged in 2020-09, with the labels that each got.

#97 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: osconfig, cla: yes, context: full

#98 chore: regenerate common templates
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#112 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: osconfig, automerge, cla: yes

#118 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#119 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
