Repository googleapis/java-os-config, pull requests merged in 2021-05, with the labels that each got.

#268 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: osconfig, automerge, cla: yes

#269 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: none

#270 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full

#272 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full

#277 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full

#278 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: osconfig, automerge, cla: yes

#276 chore: release gapic-generator-java v1.0.5
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/OsConfigServiceClient.java
  google-cloud-os-config/src/main/java/com/google/cloud/osconfig/v1/package-info.java
  google-cloud-os-config/src/test/java/com/google/cloud/osconfig/v1/OsConfigServiceClientTest.java
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full

#284 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full
